DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS models CASCADE;
DROP TABLE IF EXISTS submodels CASCADE;
DROP TABLE IF EXISTS variables CASCADE;

DROP TYPE IF EXISTS t_category;