import React from 'react'
import PaddedContainer from "../components/visual/PaddedContainer";
import {Button, Container, Text} from "native-base";
import Notifications from "react-native-push-notification";

export default class InternalDev extends React.Component {
    constructor(props) {
        super(props)
    }

    render() {
        return (
        <PaddedContainer>
            <Container>
                <Button onPress={() => {
                    Notifications.localNotification({
                        /* Android Only Properties */
                        id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
                        ticker: "My Notification Ticker", // (optional)
                        autoCancel: true, // (optional) default: true
                        largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
                        smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
                        bigText: "It's time to take your medication.", // (optional) default: "message" prop
                        subText: "By the way, how are you feeling right now?", // (optional) default: none
                        color: "red", // (optional) default: system default
                        vibrate: true, // (optional) default: true
                        vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
                        tag: 'some_tag', // (optional) add tag to message
                        group: "group", // (optional) add group to message
                        ongoing: false, // (optional) set whether this is an "ongoing" notification

                        /* iOS only properties */
                        /*alertAction: // (optional) default: view
                        category: // (optional) default: null
                        userInfo: // (optional) default: null (object containing additional notification data)
                        */

                        /* iOS and Android properties */
                        title: "My Notification Title", // (optional)
                        message: "It's time to take your medication.", // (required)
                        playSound: false, // (optional) default: true
                        soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
                        number: '10', // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
                        repeatType: 'day', // (Android only) Repeating interval. Could be one of `week`, `day`, `hour`, `minute, `time`. If specified as time, it should be accompanied by one more parameter 'repeatTime` which should the number of milliseconds between each interval
                        actions: '["Good", "Bad"]',  // (Android only) See the doc for notification actions to know more
                });
                }}>
                    <Text>Local Push Notifications</Text>
                </Button>
                <Button onPress={()=> {
                    this.props.navigation.navigate("FooterTabs");
                }}>
                    <Text>Main App</Text>
                </Button>
            </Container>
        </PaddedContainer>
        )
    }
}